---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Carbon dioxide equivalent (CO2eq)** is a metric measure used to compare emission impacts from various greenhouse gases based on their relative radiative forcing effect over a specified period of time.

**Total greenhouse gases (GHG)** are the sum of CO2eq emissions from carbon dioxide, methane, and nitrous oxide from field emissions (including those associated with soils and woody biomass). Off-site emissions (i.e. transportation) are not included.

**Emission reduction coefficients (ERC)** were calculated using a sample-based approach and model runs in <a href="http://comet-farm.com/" target="_blank"> COMET-Farm</a>, which uses USDA greenhouse gas inventory methods. More information on quantification methods can be found in the <a href="https://planner-prod2-dot-comet-201514.appspot.com/static/media/COMET-Planner_Report_Final.41c0b5e0.pdf/" target="_blank"> COMET-Planner Report</a>.

**Close this box by clicking the Minus button in the top right heading.**
