---
title: "Washington Climate Smart Estimator Report"
date: "**`r tools::toTitleCase(params$project)`** report generated by **`r tools::toTitleCase(params$name)`** on `r format(Sys.time(), ' %B %d, %Y')`"
geometry: "left=1cm,right=1cm,top=2cm,bottom=2cm"
mainfont: Arial
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \lhead{WaCSE reported generated on `r Sys.Date()`}
  - \rhead{`r paste(tools::toTitleCase(params$name), tools::toTitleCase(params$project))`}
  - \rfoot{Page \thepage}

output: 
  pdf_document:
    latex_engine: xelatex
classoption: landscape
params: 
  name: NA
  project: NA
  table: NA
  summary: NA
  plot: NA
---

```{r setup, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(kableExtra)
library(dplyr)
library(ggplot2)
```


```{r table}
options(knitr.kable.NA = "Not estimated")

df <- janitor::adorn_totals(params$table)

kbl_all <- kbl(df,
    col.names = c("MLRA",
                  "County",
                  "Class",
                  "Practice",
                  "Implementation",
                  "Acres",
                  "Carbon Dioxide",
                  "Nitrous Oxide",
                  "Methane",
                  "Total GHG"
                  ),
    caption = "Approximate Greenhouse Gas (GHG) Emission Reductions",
    align = "lllllrrrrr",
    format.args = list(big.mark = ","),
    escape = FALSE,
    booktabs = TRUE) %>%
  add_header_above(c(" " = 6, "(Metric tonnes CO2eq per year)" = 4), italic = TRUE) %>% 
  kable_styling(full_width = TRUE) %>%
  row_spec(row = 0, bold = TRUE) %>%
  column_spec(column = c(1:2), width = "0.8in") %>%
  column_spec(column = c(3:5), width = "1in") %>%
  column_spec(column = c(6:10), width = "0.8in") %>% 
  collapse_rows(columns = 1) %>% 
  row_spec(dim(df)[1], bold = TRUE)

kbl_all
```


```{r summary}

summary_df <- janitor::adorn_totals(params$summary)

kbl_summary <- kbl(summary_df,
    col.names = c("MLRA",
                  "County",
                  "Unique Practice Implementations",
                  "Total Acres",
                  "Total GHG (MT CO2eq/yr)"
                  ),
    caption = "Summary of Total GHG Emission Reductions by County",
    align = "llrrr",
    format.args = list(big.mark = ","),
    escape = FALSE,
    booktabs = TRUE) %>%
  row_spec(row = 0, bold = TRUE) %>%
  column_spec(column = c(1,3,5), width = "1.4in") %>% 
  column_spec(column = c(2,4), width = "0.8in") %>%
  collapse_rows(columns = 1) %>% 
  row_spec(dim(summary_df)[1], bold = TRUE)

kbl_summary
```


```{r plot, fig.align = "center", fig.height = 6, fig.width = 10, dpi = 300}

params$plot

```
